### ISSUE TITLE
 Expected a value of type 'FutureOr<Map<String, dynamic>>', but got one of type '_Future<Map<String, dynamic>?>'

### ISSUE THREAD

**Issue by SethKitchen** [TesteurManiak/image_picker_web_redux#8]
Hi, thanks for porting to Flutter 2.0! When I run:

```dart
MediaInfo mediaInfo = await ImagePickerWeb.getImageInfo;
```

I get:

Error: Expected a value of type 'FutureOr<Map<String, dynamic>>', but got one of type '_Future<Map<String, dynamic>?>'
    at Object.throw_ [as throw] (http://localhost:62121/dart_sdk.js:5032:11)
    at Object.castError (http://localhost:62121/dart_sdk.js:5005:15)
    at Object.cast [as as] (http://localhost:62121/dart_sdk.js:5314:17)
    at Function.as_FutureOr (http://localhost:62121/dart_sdk.js:4648:21)
    at getImageInfo (http://localhost:62121/packages/image_picker_web_redux/image_picker_web_redux.dart.lib.js:287:61)
    at getImageInfo.next (<anonymous>)
    at runBody (http://localhost:62121/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:62121/dart_sdk.js:37260:7)
    at Function.get getImageInfo [as getImageInfo] (http://localhost:62121/packages/image_picker_web_redux/image_picker_web_redux.dart.lib.js:286:20)
    at PlayerEditPageDefaultState.PlayerEditPageDefaultState.new.<anonymous> (http://localhost:62121/packages/athelite/Pages/PlayerEditPage.dart.lib.js:9322:87)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:62121/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:62121/dart_sdk.js:37260:7)
    at http://localhost:62121/packages/athelite/Pages/PlayerEditPage.dart.lib.js:9321:810
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:62121/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:62121/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:62121/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:62121/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:62121/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:62121/packages/flutter/src/gestures/arena.dart.lib.js:221:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:334:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:62121/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:62121/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:62121/dart_sdk.js:173249:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:62121/dart_sdk.js:155201:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:62121/dart_sdk.js:155815:49)
    at http://localhost:62121/dart_sdk.js:156224:26
    at http://localhost:62121/dart_sdk.js:156183:16
    at http://localhost:62121/dart_sdk.js:155908:11

I will look in repo and see if I can find::::::

**Comment by TesteurManiak** [comment]
Hi, could you provide the result of your `flutter doctor -v` and which version of the package you are using. I've tested the method that I am using in the `example/` and got no issues.

**Comment by TesteurManiak** [comment]
> Hi, could you provide the result of your `flutter doctor -v` and which version of the package you are using. I've tested the method that I am using in the `example/` and got no issues.
> (Also which browser you are using)

Okay I think I have the answer it is probably because the example is running with `unsound nullsafety` I'll merge your pull request right after it pass the required statuses.

**Comment by SethKitchen** [comment]
Yes I think we solved it -- I will close feel free to reopen
